PROJECT=obagent
PROCESSOR=2
VERSION=4.2.2-20240108
PWD ?= $(shell pwd)

GO              := GO111MODULE=on GOPROXY=https://goproxy.cn,direct go
BUILD_FLAG      := -p $(PROCESSOR)
GOBUILD         := $(GO) build $(BUILD_FLAG)
GOBUILDCOVERAGE := $(GO) test -covermode=count -coverpkg="../..." -c .
GOCOVERAGE_FILE := tests/coverage.out
GOCOVERAGE_REPORT := tests/coverage-report
GOTEST          := OB_AGENT_CONFIG_PATH=$(PWD) $(GO) test -tags test -covermode=count -coverprofile=$(GOCOVERAGE_FILE) -p $(PROCESSOR)

GO_RACE_FLAG =-race
LDFLAGS += -X "github.com/oceanbase/obagent/config.AgentVersion=${VERSION}"
LDFLAGS += -X "github.com/oceanbase/obagent/config.BuildEpoch=$(shell date '+%s')"
LDFLAGS += -X "github.com/oceanbase/obagent/config.BuildGoVersion=$(shell go version)"
LDFLAGS += -X "github.com/oceanbase/obagent/config.GitBranch=$(shell git rev-parse --abbrev-ref HEAD)"
LDFLAGS += -X "github.com/oceanbase/obagent/config.GitCommitId=$(shell git rev-parse HEAD)"
LDFLAGS += -X "github.com/oceanbase/obagent/config.GitShortCommitId=$(shell git rev-parse --short HEAD)"
LDFLAGS += -X "github.com/oceanbase/obagent/config.GitCommitTime=$(shell git log -1 --format=%cd)"
LDFLAGS_DEBUG = -X "github.com/oceanbase/obagent/config.Mode=debug"
LDFLAGS_RELEASE = -X "github.com/oceanbase/obagent/config.Mode=release"
MGRAGENT_LDFLAGS = $(LDFLAGS) -X "github.com/oceanbase/obagent/config.CurProcess=ob_mgragent"
MONAGENT_LDFLAGS = $(LDFLAGS) -X "github.com/oceanbase/obagent/config.CurProcess=ob_monagent"
AGENTCTL_LDFLAGS = $(LDFLAGS) -X "github.com/oceanbase/obagent/config.CurProcess=ob_agentctl"
AGENTD_LDFLAGS = $(LDFLAGS) -X "github.com/oceanbase/obagent/config.CurProcess=ob_agentd"

GOFILES ?= $(shell git ls-files '*.go')
GOTEST_PACKAGES = $(shell go list ./... | grep -v -f tests/excludes.txt)
UNFMT_FILES ?= $(shell gofmt -l -s $(filter-out , $(GOFILES)))

